# Generated by Django 5.0.1 on 2025-10-20 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAISSIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index_name", models.CharField(max_length=255, unique=True)),
                ("index_file_path", models.CharField(max_length=500)),
                ("metadata_file_path", models.CharField(max_length=500)),
                (
                    "dimension",
                    models.IntegerField(
                        default=384, help_text="Embedding dimension (384 for MiniLM)"
                    ),
                ),
                ("total_vectors", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "documents_included",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of Document IDs included in this index",
                    ),
                ),
            ],
            options={
                "db_table": "faiss_indexes",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["index_name"], name="faiss_index_index_n_b9815f_idx"
                    ),
                    models.Index(
                        fields=["-last_updated"], name="faiss_index_last_up_c4db85_idx"
                    ),
                ],
            },
        ),
    ]
