# Generated by Django 5.0.1 on 2025-10-20 06:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["-last_updated"], name="conversatio_last_up_05ea32_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="conversatio_session_69cb64_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_chunks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of Chunk IDs used for this response",
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to audio file for voice messages",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores citations, confidence scores, etc.",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["conversation", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "timestamp"],
                        name="messages_convers_31a2d0_idx",
                    ),
                    models.Index(fields=["role"], name="messages_role_8be1df_idx"),
                ],
            },
        ),
    ]
