# Generated by Django 5.0.1 on 2025-10-20 06:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("page_count", models.IntegerField(default=0)),
                (
                    "upload_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-upload_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-upload_timestamp"],
                        name="documents_upload__fc4521_idx",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="documents_process_e1e618_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField(help_text="Order within document")),
                ("page_number", models.IntegerField()),
                ("chunk_text", models.TextField()),
                ("chunk_token_count", models.IntegerField(default=0)),
                ("start_char_index", models.IntegerField(default=0)),
                ("end_char_index", models.IntegerField(default=0)),
                (
                    "embedding_vector_id",
                    models.CharField(
                        blank=True,
                        help_text="Maps to FAISS index position",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="chunks_documen_a11b61_idx",
                    ),
                    models.Index(
                        fields=["embedding_vector_id"], name="chunks_embeddi_0c0fe9_idx"
                    ),
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
