# Generated by Django 5.0.1 on 2025-10-20 06:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_audio_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to input audio file (for STT)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "output_audio_path",
                    models.CharField(
                        help_text="Path to output audio file (for TTS)", max_length=500
                    ),
                ),
                (
                    "voice_model",
                    models.CharField(
                        default="alloy",
                        help_text="Voice model used (alloy, nova, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        default=0.0, help_text="Audio duration in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_interactions",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "voice_interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="voice_inter_created_8a41c4_idx"
                    ),
                    models.Index(
                        fields=["message"], name="voice_inter_message_0533fa_idx"
                    ),
                ],
            },
        ),
    ]
